name: practica-3-threepoints-ci-cd
run-name: ${{ github.actor }} - Practica 3 - Threepoints - CI/CD
on: [push]
jobs:
  continous-integration-andres-ospina:
    runs-on: ubuntu-latest    
    steps:    
    - name: Pruebas de SAST
      env:
        user : ${{secrets.USERNAME}}
      run: echo "Ejecucion de pruebas de SAST"
    - uses: actions/checkout@v2.3.4
    - uses: GuillaumeFalourd/command-output-file-action@v1.1
      id: sast
      with:
        command_line: echo "[credentials] username=${{ env.user }} password=${{ secrets.PASSWORD }}"
        output_file_name: credentials.ini
        display_file_content: YES
